stages:
  - static_analysis
  - test
  - qa_build_validation
  - qa_build
  - release_build

lint:
  stage: static_analysis
  script:
    make lint
  artifacts:
    paths:
      - lint-report
    expire_in: 1 day
  only:
    - merge_request
  tags:
    - ios

unit_tests:
  stage: test
  script:
    - make test | tee -a test.log
  artifacts:
    when: always
    paths:
      - test.log
      - TestResults.xcresult
      - test-coverage-report.txt
    expire_in: 1 day
  only:
    - merge_request
  tags:
    - ios

qa_build_validation:
  stage: qa_build_validation
  script:
    make qa_build_validation | tee -a validation.log
  artifacts:
    when: always
    paths:
      - validation.log
    expire_in: 1 day
  only:
    - merge_request
  tags:
    - ios

qa_build_upload:
  stage: qa_build
  script:
    make qa_build_publish | tee -a upload.log
  artifacts:
    when: always
    paths: 
    - upload.log
    - Passbolt.ipa
    expire_in: 1 day
  only:
    - develop
  tags:
    - ios

release_build_upload:
  stage: release_build
  script:
    make release_build_publish | tee -a upload.log
  artifacts:
    when: always
    paths: 
    - upload.log
    - Passbolt.ipa
    expire_in: 1 month
  only:
    - /^release.*$/
  tags:
    - ios
